# Generated by Django 4.1.2 on 2022-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ide', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=155)),
                ('apellido', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
    ]
