# Generated by Django 4.1.2 on 2022-10-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_apellido_alter_empleado_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
    ]
